language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - jruby
  - rbx
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git libtool autoconf automake
before_script:
  - git clone https://github.com/sipa/secp256k1 -b context
  - cd secp256k1
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - sudo bash -c 'echo /usr/local/lib > /etc/ld.so.conf.d/local.conf'
  - sudo ldconfig